### ISSUE TITLE
FFmpeg seems to be missing

### ISSUE THREAD

**Issue by tmolter** [MichaelGDev48/citra-nightly-arm64-mac#2] opened 2022-10-10 05:23 UTC
The dump video button under Tools is grayed out. Not 100% sure but pretty sure it's cause FFmpeg is missing from the build. I'd add it into my own build but I've got zero clue where it'd even go.

**Comment by MichaelGDev48** [comment] 2022-11-22 07:27
On the next release Ill see what I can do

**Comment by DarthMDev** [comment] 2023-01-01 20:35
Problem should be fixed with the experimental vulkan release

**Comment by tmolter** [comment] 2023-01-02 01:07
Awesome! I’ll give it a go tonight and let you know if its good

**Comment by tmolter** [comment] 2023-01-02 02:17
![image](https://user-images.githubusercontent.com/16199022/210191050-1043a5f2-7e3a-4a43-b7d8-e19b24ee05b1.png)

I get this error when trying to open the new build

**Comment by DarthMDev** [comment] 2023-01-02 02:48
For now brew install ffmpeg i need to talk to some devs on how to change this

**Comment by tmolter** [comment] 2023-01-02 03:09
you're so going to hate me lol but i already have ffmpeg installed through homebrew

just lemme know when you hear back from someone about this cause i am lowkey dying to try out vullkan on citra

**Comment by DarthMDev** [comment] 2023-01-02 07:01
well try reinstalling it bc u have a x86_64 version for some reason

**Comment by tmolter** [comment] 2023-01-02 18:47
tried removing all my homebrew packages and reinstalling, still am getting the same error. I might be installing ffmpeg wrong but ive got no clue at this point 
![image](https://user-images.githubusercontent.com/16199022/210269186-f5850925-d8ac-4a48-a26b-df6b8382f067.png)

**Comment by grishhung** [comment] 2023-01-02 20:24
Just wanted to echo the above comments -- I also have the ARM version of ffmpeg installed via homebrew. There's no x86 version on here, as far as I can tell. The build crashes immediately. Not sure what to do to get around that.
<img width="1112" alt="Screenshot_2023-01-02_at_3 22 37_PM" src="https://user-images.githubusercontent.com/93692315/210275429-77f4886a-76c9-4bef-85f8-cd6f0515138a.png">

**Comment by DarthMDev** [comment] 2023-01-03 08:27
try this latest build pls
[MichaelGDev48/citra-nightly-arm64-mac/suites/10152053607/artifacts/496037583](https://github.com/MichaelGDev48/citra-nightly-arm64-mac/suites/10152053607/artifacts/496037583)

**Comment by tmolter** [comment] 2023-01-03 16:36
Uhh well its kind of fixed, now its looking for a different dylib that it can't find or load 
![image](https://user-images.githubusercontent.com/16199022/210400287-07a1a996-6e73-4545-af05-63cde63c2cb8.png)

**Comment by DarthMDev** [comment] 2023-01-03 16:45
yep ok and this build?
https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3828463326

**Comment by tmolter** [comment] 2023-01-03 18:09
This is what i get for this one 
![image](https://user-images.githubusercontent.com/16199022/210415907-2cb8fe92-b637-4537-ba75-1a554acf2268.png)

**Comment by DarthMDev** [comment] 2023-01-03 18:13
Really getting tired of ffmpeg 😒

**Comment by tmolter** [comment] 2023-01-03 18:20
honestly just try to compile it without it lol. The only reason i had asked about it in the first place is because I prefer using Citra's dump video feature for showcasing 3ds mods that I'm working on

**Comment by tmolter** [comment] 2023-01-03 18:21
I can live with OBS its not a big deal

**Comment by DarthMDev** [comment] 2023-01-03 18:44
Ok thank you ill eventually try to compile it manually for arm64 again instead of universal2  but for now
Check back here 30 mins - hour for macos build
https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3832111487

**Comment by DarthMDev** [comment] 2023-01-03 19:00
im also currently in the process of manually compiling for just arm64 with my system 
that should have ffmpeg no problem

**Comment by MichaelGDev48** [comment] 2023-01-03 19:14
try this build for ur ffmpeg needs
https://cdn.discordapp.com/attachments/933416971146493983/1059912416374309014/citra-osx-20230103-c2178c3de.7z

**Comment by tmolter** [comment] 2023-01-03 19:44
Okay so the new build actually seems to be working... however i cant get into preferences to actually turn on vullkan 😭
![image](https://user-images.githubusercontent.com/16199022/210429830-5628e134-bbb7-4101-af72-6e0105d040b1.png)

**Comment by DarthMDev** [comment] 2023-01-03 19:45
Yeah thats not a bug with my build thats a citra thing
For now edit it in ~/.config/ 
Will be in the citra directory 
Will be a .ini file

**Comment by tmolter** [comment] 2023-01-03 19:48
do you know what line in the ini file to edit?

**Comment by DarthMDev** [comment] 2023-01-03 19:52
qt-config.ini
under Renderer
graphics_api=2
graphics_api\default=false

**Comment by tmolter** [comment] 2023-01-03 20:07
this might be a bit beyond you at this point but i just get a crash when opening up a game even afer changing my stuff in the ini file 
![image](https://user-images.githubusercontent.com/16199022/210433165-5b8cef6d-b05b-427a-9ee0-61d219d619cc.png)

**Comment by DarthMDev** [comment] 2023-01-03 20:08
looks like something to report to the vulkan guy
join the citra discord and report it under #vulkan-testing 
https://discord.gg/FAXfZV9

**Comment by tmolter** [comment] 2023-01-03 20:44
Will do. Thank you for all the help, really appreciate it!

**Comment by DarthMDev** [comment] 2023-01-05 04:26
can you try this i might've gotten ffmpeg thing right
https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3843729242

**Comment by tmolter** [comment] 2023-01-05 20:11
Ayee its working now. Still get a crash when trying to load games but the app itself seems to run fine

**Comment by DarthMDev** [comment] 2023-01-05 20:12
awesome glad to hear ffmpeg is sorted 
can you send a log of citra itself not the mac app crash

**Comment by tmolter** [comment] 2023-01-05 22:10
[citra_log.txt](https://github.com/MichaelGDev48/citra-nightly-arm64-mac/files/10355970/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/MichaelGDev48/citra-nightly-arm64-mac/files/10355971/citra_log.txt.old.txt)

**Comment by DarthMDev** [comment] 2023-01-05 23:56
Hmm can you run it in terminal and show me output

**Comment by dravpin** [comment] 2023-01-06 00:04
yup citra runs now.... but crashes with every game

**Comment by tmolter** [comment] 2023-01-06 03:51
Yep! Got it right here 
![image](https://user-images.githubusercontent.com/16199022/210926541-cbae2043-b0a5-4567-87fb-123aa40aa115.png)

**Comment by DarthMDev** [comment] 2023-01-06 05:17
Ah i see something with vulkan im on it

**Comment by tmolter** [comment] 2023-01-06 05:26
it also might be worth noting that the preference pane in the menu bar isnt grayed out, but still does crash (pretty sure you mentioned tho that its an issue with citra itself)

**Comment by DarthMDev** [comment] 2023-01-06 05:57
i pushed a change hopefully it fixes it when its done building
https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3853006839

**Comment by tmolter** [comment] 2023-01-06 06:27
Everything seems to be up and working!! Some of my graphics settings seem to be grayed out and I can't turn on hardware shader (which i would hope would improve performance) but other than that i think its good to go

**Comment by DarthMDev** [comment] 2023-01-06 06:29
finally thank god 
graphics settings should only be grayed out with in-game settings
alternatively if u cant access the global preferences for some reason 
~/.config/citra-emu/qt-config.ini
use_hw_shader=true

**Comment by tmolter** [comment] 2023-01-06 06:40
Oh right lol, kinda forgot about that

Okay yeah this is a HUGE performance boost, Super Mario 3D Land is running at 8x Native and isn't dropping any frames! 
![image](https://user-images.githubusercontent.com/16199022/210944902-618e41b5-e68d-44fd-b4c9-98ca838e19cd.png)

**Closed** 2023-01-06 06:44 UTC
