### ISSUE TITLE
can't open citra-qt

### ISSUE THREAD

**Issue by Sylvia34343** [MichaelGDev48/citra-nightly-arm64-mac#9] opened 2023-01-03 01:58 UTC
I download the version published on Jan 1. My laptop is Mac M1 pro. The system is Ventura 13.1. 
The problem is that I can't open citra-qt. Each time I try to open it, it says citra-qt quit unexpectedly.

mising lib
/Users/runner/work/FFmpeg-macOS/FFmpeg-macOS/ffmpeg/install_universal/lib/libavcodec.59.dylib

**Comment by DarthMDev** [comment] 2023-01-03 18:48
duplicate of #8 

Check back here 30 mins - hour for macos build
[MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3832111487](https://github.com/MichaelGDev48/citra-nightly-arm64-mac/actions/runs/3832111487)

**Closed as completed by DarthMDev** 2023-01-03 18:48 UTC
